---
- name: Install OpenJDK 8
  apt: name={{item}} state=latest
  with_items:
    - openjdk-8-jdk
  sudo: yes
  tags: [package, java8]


- name: Set java8 as default java
  alternatives: name=java path=/usr/lib/jvm/java-8-openjdk-amd64/bin/java
  sudo: yes
  tags: [configuration, java8]
