---
- hosts: local
  tasks:
    - name: install nix
      command: bash -c "curl https://nixos.org/nix/install | sh"
      args:
        creates: /nix

    - name: install HTTPS apt
      apt: pkg=apt-transport-https state=latest
      sudo: yes

- hosts: local
  roles:
  - skel
  - common
  - spotify
  - java8
  - node
  - emacs
  - docker
