- name: install basic development tools
  nix: name={{item}} state=present
  with_items:
     - git
     - silver-searcher

- name: install basic development tools
  apt: pkg={{item}} state=latest
  with_items:
     - editorconfig
  sudo: yes

- include: node.yml
- include: emacs.yml
