---
- name: Add Docker Key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  sudo: yes
  tags: [package, docker]

- name: Add Docker APT repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo debian-stretch main'
    state: 'present'
    update_cache: 'yes'
  sudo: yes
  tags: [package, docker]

- name: install node
  apt: pkg=docker-engine state=latest
  sudo: yes
  tags: [package, docker]

- name: dotfiles docker
  command: stow -R --no-folding docker
  args:
    chdir: ~/.dotfiles
  tags: [dotfiles, docker]
